Algo- array: finding shortest sub-array that has to be sorted to sort the entire array
thepranaygupta/Data-Structures-and-Algorithms pull request #124
Opened 2021-10-02 02:51 UTC by O-alpha

Finds the shortest unsorted sub-array which when sorted can sort the entire array in O(n) time complexity and O(1) space complexity
link: https://www.geeksforgeeks.org/minimum-length-unsorted-subarray-sorting-which-makes-the-complete-array-sorted/

2021-10-02 02:52 UTC, O-alpha commented
@thepranaygupta please check this out. thanks!

2021-10-02 15:07 UTC, thepranaygupta requested changes
please create a new directory containing this `.cpp` file and a `README.md` file.
Check other folders for reference 👍

2021-10-02 16:09 UTC, O-alpha commented
@thepranaygupta readme.md file has been added, there's no code included in it however; the entire code provided in the .cpp file is the algorithm.

2021-10-03 08:56 UTC, thepranaygupta approved these changes

2021-10-03 08:56 UTC, merged